name: {{ cookiecutter.docker_compose_name }}

services:
  {{ cookiecutter.service_name }}:
    image: "${DOCKER_IMAGE_NAME}"
    platform: "${DOCKER_BUILD_PLATFORM}"
    tty: true
    stdin_open: true
    links:
      - redis
      - postgres
    volumes:
      - "${CURDIR}:${DOCKER_MOUNT_POINT}"
    ports:
      # This configuration binds port of the container to the host's TCP port.
      # If no specific IP address is provided, Docker will bind the port to all network
      # interfaces (0.0.0.0). As a result, the exposed port will be accessible
      # externally.
      - "127.0.0.1:${DOCKER_HOST_PORT}:${DOCKER_CONTAINER_PORT}"
    expose:
      - "${DOCKER_CONTAINER_PORT}"
    environment:
      # Logging
      {{ cookiecutter.env_prefix }}LOG_LEVEL: "info"
      {{ cookiecutter.env_prefix }}LOG_FORMAT: "console"
      {{ cookiecutter.env_prefix }}LOG_COLORS: "true"
      {{ cookiecutter.env_prefix }}LOG_VERBOSE: "true"
      # Database
      {{ cookiecutter.env_prefix }}DATABASE_URL: "postgresql+asyncpg://{{ cookiecutter.postgres_user }}:{{ cookiecutter.postgres_user }}@postgres:5432/{{ cookiecutter.postgres_user }}"
    command: [
      "-c",
      "./docker/scripts/wait_for_pg.py \
      && /bin/bash"
    ]

  redis:
    image: "redis:{{ cookiecutter.redis_image_tag }}"

  postgres:
    image: "postgres:{{ cookiecutter.postgres_image_tag }}"
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_USER: "{{ cookiecutter.postgres_user }}"
      POSTGRES_PASSWORD: "{{ cookiecutter.postgres_user }}"
      POSTGRES_DB: "{{ cookiecutter.postgres_user }}"
